name: linux-build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to build'
        required: true
        default: 'master'

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install Tauri CLI
        run: cargo install tauri-cli

      - name: Install Linux Dependencies for   Tauri and WebKitGTK
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.0-dev \
            libjavascriptcoregtk-4.0-dev \
            javascriptcoregtk-4.1-dev \
            webkit2gtk-4.1-dev \
            libgtk-3-dev \
            libgdk-pixbuf-2.0-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            libsoup-3.0-dev \
            build-essential \
            curl \
            wget \
            libssl-dev

      - name: Install Project Dependencies
        run: npm install

      - name: Build Linux App with Cargo
        run: |
          cd src-tauri
          cargo tauri build
        env:
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          VITE_STRIPE_PUBLISHABLE_KEY: ${{ secrets.VITE_STRIPE_PUBLISHABLE_KEY }}

      - name: Upload Linux Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-app-build
          path: src-tauri/target/release/cipher
